#!/bin/bash -e

source $(dirname $0)/functions
source $(dirname $0)/pkgversion

filename=$(echo $0 | rev | cut -d / -f1 | rev)

TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}

NAME=binutils
VERSION=${BINUTILS_VER}

fetch "http://ftp.gnu.org/gnu/binutils/$NAME-$VERSION.tar.xz" $SRC

[ "$1" = "fetch" ] && exit 0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC

tar xf $SRC/$tarballname -C $TMP

{ time \
   {

	cd $TMP/$NAME-$VERSION
	
	mkdir -v build
	cd build
	
	AR=ar AS=as \
	../configure \
		--prefix=/cross-tools \
		--host=${CLFS_HOST} \
		--target=${CLFS_TARGET} \
		--with-sysroot=${CLFS} \
		--with-lib-path=/tools/lib:/tools/lib64 \
		--disable-nls \
		--disable-static \
		--enable-64-bit-bfd \
		--enable-gold=yes \
		--enable-plugins \
		--enable-threads \
		--disable-werror
	make
	make install
	
	}
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$NAME-$VERSION" > /tools/$filename || exit $PIPESTATUS

rm -fr $TMP
