#!/bin/bash -e

source $(dirname $0)/functions
source $(dirname $0)/pkgversion

filename=$(echo $0 | rev | cut -d / -f1 | rev)

TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}

NAME=glibc
VERSION=${GLIBC_VER}

fetch "http://ftp.gnu.org/gnu/glibc/$NAME-$VERSION.tar.xz" $SRC

[ "$1" = "fetch" ] && exit 0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC

tar xf $SRC/$tarballname -C $TMP

{ time \
   {

	cd $TMP/$NAME-$VERSION
	
	mkdir build
	cd build
	
	BUILD_CC="gcc" CC="${CLFS_TARGET}-gcc ${BUILD32}" \
	AR="${CLFS_TARGET}-ar" RANLIB="${CLFS_TARGET}-ranlib" \
	../configure \
		--prefix=/tools \
		--host=${CLFS_TARGET32} \
		--build=${CLFS_HOST} \
		--enable-kernel=3.12.0 \
		--with-binutils=/cross-tools/bin \
		--with-headers=/tools/include \
		--enable-obsolete-rpc
	make
	make install
	
	}
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$NAME-$VERSION" > /tools/$filename || exit $PIPESTATUS

rm -fr $TMP
