#!/bin/bash -e

source $(dirname $0)/functions
source $(dirname $0)/functions-extra
source $(dirname $0)/pkgversion

filename=$(echo $0 | rev | cut -d / -f1 | rev)

TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}

NAME=gcc
VERSION=${GCC_VER}

fetch "http://patches.clfs.org/sysvinit/$NAME-7.1.0-specs-1.patch" $SRC
fetch "ftp://gcc.gnu.org/pub/gcc/releases/$NAME-$VERSION/$NAME-$VERSION.tar.xz" $SRC

[ "$1" = "fetch" ] && exit 0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC

tar xf $SRC/$tarballname -C $TMP
cp $SRC/$NAME-7.1.0-specs-1.patch $TMP

{ time \
   {

	cd $TMP/$NAME-$VERSION

	patch -Np1 -i ../$NAME-7.1.0-specs-1.patch
	
	echo -en '\n#undef STANDARD_STARTFILE_PREFIX_1\n#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"\n' >> gcc/config/linux.h
	echo -en '\n#undef STANDARD_STARTFILE_PREFIX_2\n#define STANDARD_STARTFILE_PREFIX_2 ""\n' >> gcc/config/linux.h

	cp -v gcc/Makefile.in{,.orig}
	sed 's@\./fixinc\.sh@-c true@' gcc/Makefile.in.orig > gcc/Makefile.in

	mkdir build
	cd build
	
	../configure \
		--prefix=/tools \
		--libdir=/tools/lib64 \
		--build=${CLFS_HOST} \
		--host=${CLFS_TARGET} \
		--target=${CLFS_TARGET} \
		--with-local-prefix=/tools \
		--enable-languages=c,c++ \
		--with-system-zlib \
		--with-native-system-header-dir=/tools/include \
		--disable-libssp \
		--enable-install-libiberty
	make AS_FOR_TARGET="${AS}" \
		LD_FOR_TARGET="${LD}"
	make install
	
	}
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$NAME-$VERSION" > /tools/$filename || exit $PIPESTATUS

rm -fr $TMP
