#!/bin/bash -e

source $(dirname $0)/functions
source $(dirname $0)/functions-extra
source $(dirname $0)/pkgversion

filename=$(echo $0 | rev | cut -d / -f1 | rev)

TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}

NAME=bzip2
VERSION=${BZIP_VER}

fetch "http://www.bzip.org/$VERSION/$NAME-$VERSION.tar.gz" $SRC

[ "$1" = "fetch" ] && exit 0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC

tar xf $SRC/$tarballname -C $TMP

{ time \
   {

	cd $TMP/$NAME-$VERSION

	cp -v Makefile{,.orig}
	sed -e 's@^\(all:.*\) test@\1@g' \
		-e 's@/lib\(/\| \|$\)@/lib64\1@g' Makefile.orig > Makefile
	make CC="${CC}" AR="${AR}" RANLIB="${RANLIB}"
	make PREFIX=/tools install
	
	}
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$NAME-$VERSION" > /tools/$filename || exit $PIPESTATUS

rm -fr $TMP
