#!/bin/bash -e

source $(dirname $0)/functions
source $(dirname $0)/functions-extra
source $(dirname $0)/pkgversion

filename=$(echo $0 | rev | cut -d / -f1 | rev)

TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}

NAME=util-linux
VERSION=${UTILLINUX_VER}

fetch "http://www.kernel.org/pub/linux/utils/util-linux/v${VERSION::4}/$NAME-$VERSION.tar.xz" $SRC

[ "$1" = "fetch" ] && exit 0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC

tar xf $SRC/$tarballname -C $TMP

{ time \
   {

	cd $TMP/$NAME-$VERSION

	./configure \
		--prefix=/tools \
		--build=${CLFS_HOST} \
		--host=${CLFS_TARGET} \
		--libdir='${prefix}'/lib64 \
		--disable-makeinstall-chown \
		--without-systemdsystemunitdir \
        --without-ncurses \
		--without-python \
        PKG_CONFIG=""
	make
	make install
	
	}
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$NAME-$VERSION" > /tools/$filename || exit $PIPESTATUS

rm -fr $TMP
