#!/bin/bash -e

filename=$(echo $0 | rev | cut -d / -f1 | rev)

TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}
MAKEFLAGS=${MAKEFLAGS:-"-j2"}

BUILD64="-m64"

export MAKEFLAGS

NAME=tcl-core
VERSION=8.6.8
URL=http://downloads.sourceforge.net/tcl/${NAME}${VERSION}-src.tar.gz

wget -nc $URL -P $SRC

[ "$1" = "fetch" ] && exit 0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC

tar xf $SRC/${NAME}${VERSION}-src.tar.gz -C $TMP

{ time \
   {

	cd $TMP/tcl${VERSION}

	cd unix
	CC="gcc ${BUILD64}" ./configure \
		--prefix=/tools \
		--libdir=/tools/lib64
	make
	make install
	make install-private-headers
	ln -sv tclsh8.6 /tools/bin/tclsh
	
	}
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -fr $TMP

exit 0
