#!/bin/bash -e

filename=$(echo $0 | rev | cut -d / -f1 | rev)

TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}
MAKEFLAGS=${MAKEFLAGS:-"-j2"}

BUILD64="-m64"

export MAKEFLAGS

NAME=expect
VERSION=5.45.4
URL=http://downloads.sourceforge.net/project/expect/Expect/$VERSION/expect$VERSION.tar.gz

wget -nc $URL -P $SRC

[ "$1" = "fetch" ] && exit 0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC

tar xf $SRC/expect$VERSION.tar.gz -C $TMP

{ time \
   {

	cd $TMP/expect${VERSION}

	CC="gcc ${BUILD64}" \
	./configure \
		--prefix=/tools \
		--with-tcl=/tools/lib64 \
		--with-tclinclude=/tools/include \
		--libdir=/tools/lib64
	make
	make SCRIPTS="" install
	
	}
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -fr $TMP

exit 0
