#!/bin/bash -e

filename=$(echo $0 | rev | cut -d / -f1 | rev)

TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}
MAKEFLAGS=${MAKEFLAGS:-"-j2"}

BUILD64="-m64"

export MAKEFLAGS

NAME=dejagnu
VERSION=1.6.1
URL=http://ftp.gnu.org/gnu/dejagnu/$NAME-$VERSION.tar.gz

wget -nc $URL -P $SRC

[ "$1" = "fetch" ] && exit 0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC

tar xf $SRC/$NAME-$VERSION.tar.gz -C $TMP

{ time \
   {

	cd $TMP/$NAME-$VERSION

	./configure \
		--prefix=/tools
	make install
	
	}
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

rm -fr $TMP

exit 0
